trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    version: '20.11.0'
  displayName: 'Install Node.js'

- script: |
    cd Backend
    npm install --legacy-peer-deps
  displayName: 'npm install'

- script: |
    cd Backend
    npm run start
  displayName: 'npm start'
